### PR TITLE
Added Norwegian language (nb_NO)

### PR DESCRIPTION
**Pull request by olean-b**
Great if you could also please update the extension in mBlock Extension Center.

### CODE REVIEW

**Comment by SamGriffen** [comment]
Thanks! Updating the extension now

**Comment by SamGriffen** [comment]
I have been attempting to add it to the extension centre, it seems that the extension centre doesn't like the translation for some reason? The translation definitely works on my machine, however it gets rejected when I try to upload.

**Comment by SamGriffen** [comment]
Being thorough, I tried uploading it without the translation code, and it worked... any ideas on a solution?

**Comment by olean-b** [comment]
That’s odd. I have no experience in publishing these extensions. Just copied the Demo- code, which contains a Chinese translation.
 
Maybe the Norwegian letters are rejected? What if you replace ‘ø’ with ‘oe’. That’s a, more or less, common replacement.

**Pull request merged**
